export * from '@services/processos/get/getProcesso.services'
export * from '@services/processos/get/getCadatroProcesso.services'
export * from '@services/processos/get/getIdsProcessoColetivo.services'
export * from '@services/processos/utils/extractIdProcessoFromUrl.services'
export * from '@services/processos/utils/extrairDadosRequisicaoProcessoColetivoDemaisEnvolvidosHtml.services'
export * from '@services/processos/utils/extrairDadosRequisicaoProcessoHtml.services'
export * from '@services/processos/utils/requestDataProcesso.services'
export * from '@services/processos/utils/extractValueFromSelectProcessForm.services'