export * from '@services/processos/get/getProcessoService'
export * from '@services/processos/get/getCadatroProcessoService'
export * from '@services/processos/get/getIdsProcessoColetivo'
export * from '@services/processos/utils/extractIdProcessoFromUrl'
export * from '@services/processos/utils/extrairDadosRequisicaoProcessoColetivoDemaisEnvolvidosHtml'
export * from '@services/processos/utils/extrairDadosRequisicaoProcessoHtml'
export * from '@services/processos/utils/requestDataProcesso'
export * from '@services/processos/utils/extractValueFromSelect'