import { iColaborador } from "@models/colaboradores";
import { localAtendimentoKorbil } from "./locaisAtendimento";
import { assignments } from "./assignments";

//Última atualização: 02/10/2025
// Padrão para data das viagens: ['DD/MM']
export const ADM: iColaborador[] = [
    {
        id: '256',
        nome: "CHRISTYAN RANGELL SILVA DAMASCENO XAVIER",
        nomeTLC: "CHRISTYAN",
        interiores: [localAtendimentoKorbil.se.estancia, localAtendimentoKorbil.se.tobiasBarreto],
        assignments: [assignments.ADM.contatar.geral, assignments.ADM.pendencias],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '234',
        nome: "DAVI ALVES DOS SANTOS",
        nomeTLC: "DAVI",
        interiores: [],
        assignments: [assignments.ADM.contatar.BSB],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '204',
        nome: "DIEGO DOS SANTOS SILVA",
        nomeTLC: "DIEGO SANTOS",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '238',
        nome: "ERICK RODRIGUES DE JEUS",
        nomeTLC: "ERICK",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '263',
        nome: "GUILHERME CAUAN MATOS SILVA",
        nomeTLC: "GUILHERME",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '205',
        nome: "HELTON FRADES BRABEC SOUZA",
        nomeTLC: "HELTON",
        interiores: [],
        assignments: [],
        datasViagem: null,
        tarefas: 0,
    },
    {
        id: '239',
        nome: "ISAC CRUZ SANTOS",
        nomeTLC: "ISAC",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '241',
        nome: "JEFERSON ALMEIDA SANTOS",
        nomeTLC: "JEFERSON",
        interiores: [localAtendimentoKorbil.se.carmopolis, localAtendimentoKorbil.se.pedrinhas],
        assignments: [assignments.ADM.contatar.geral, assignments.ADM.pendencias],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '197',
        nome: "JHONATHAN DA FONSECA ALMEIDA FLOR",
        nomeTLC: "JHONATHAN FONSECA",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '247',
        nome: "JHONATAN NASCIMENTO TAVARES",
        nomeTLC: "JHONATHAN NASCIMENTO",
        assignments: [],
        interiores: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '51',
        nome: "JULIANO OLIVEIRA DE SOUZA",
        nomeTLC: "JULIANO",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '221',
        nome: "LEONARDO TEIXEIRA SANTOS SILVA",
        nomeTLC: "LEONARDO",
        interiores: [localAtendimentoKorbil.se.loteamentoJeova, localAtendimentoKorbil.se.santaRosaDeLima, localAtendimentoKorbil.se.umbauba],
        assignments: [assignments.ADM.contatar.geral, assignments.ADM.pendencias],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '199',
        nome: "LUCAS NATHAN NOGUEIRA DA SILVA",
        nomeTLC: "LUCAS",
        interiores: [],
        assignments: [assignments.ADM.contatar.geral],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '201',
        nome: "MARCO AURELIO LEITE GOMES",
        nomeTLC: "MARCO AURELIO",
        interiores: [],
        assignments: [assignments.ADM.pendencias],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '231',
        nome: "MARIA LUANNA DE LIMA SOUZA",
        nomeTLC: "M. LUANNA",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '223',
        nome: "MATHEUS CAMPELO DA SILVA",
        nomeTLC: "MATHEUS CAMPELO",
        interiores: [],
        assignments: [assignments.ADM.contatar.BSB],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '198',
        nome: "MURILLO VICTOR SANTOS ROCHA",
        nomeTLC: "MURILLO",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '22',
        nome: "SANDOVAL FILHO CORREIA LIMA FILHO",
        nomeTLC: "SANDOVAL",
        interiores: [],
        assignments: [assignments.ADM.contatar.estancia],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '222',
        nome: "STEFANNY MORAIS DO NASCIMENTO",
        nomeTLC: "STEFANNY",
        interiores: [],
        assignments: [assignments.ADM.contatar.BSB],
        datasViagem: [],
        tarefas: 0,
    },
    {
        id: '217',
        nome: "THIAGO SANTOS SANTANA",
        nomeTLC: "THIAGO",
        interiores: [localAtendimentoKorbil.se.capela, localAtendimentoKorbil.se.japaratuba, localAtendimentoKorbil.ba.conde, localAtendimentoKorbil.ba.alagoinhas],
        assignments: [assignments.ADM.contatar.geral, assignments.ADM.pendencias],
        datasViagem: null,
        tarefas: 0,
    },
    {
        id: '161',
        nome: "YURI DIAS PEREIRA",
        nomeTLC: "YURI",
        interiores: [],
        assignments: [],
        datasViagem: [],
        tarefas: 0,
    },
]