export const localAtendimentoKorbil = {
    ba: {
        alagoinhas: 'ALAGOINHAS/BA',
        conde: 'CONDE/BA',
        pauloAfonso: 'PAULO AFONSO/BA',
        salvador: 'SALVADOR/BA',
    },
    df: {
        aasm: 'AASM',
        aguaQuente: 'ÁGUA QUENTE',
        associacaoMaosQueCriam: 'ASSOCIAÇÃO MÃOS QUE CRIAM',
        caritas: 'CÁRITAS/DF',
        estrutural: 'ESTRUTURAL',
        taguatinga: 'FILIAL TAGUATINGA/DF',
        planaltina: 'PLANALTINA',
        portoRico: 'PORTO RICO',
        recantoDasEmas: 'RECANTO DAS EMAS',
        riachoFundo: 'RIACHO FUNDO',
        samambaia: 'SAMAMBAIA',
        santaMaria: 'SANTA MARIA/DF',
        sobradinho: 'SOBRADINHO',
        vicentePires: 'VICENTE PIRES',
    },
    se: {
        amorimDeLimaAdvogados: 'AMORIM DE LIMA ADVOGADOS',
        assentamentoAratu: 'ASSENTAMENTO ARATÚ',
        campoDoBrito: 'CAMPO DO BRITO/SE',
        capela: 'CAPELA/SE',
        carmopolis: 'CARMÓPOLIS/SE',
        carroQuebrado: 'CARRO QUEBRADO (JAPOATÃ)',
        coloniaItaporanga: 'COLONIA ITAPORANGA/SE',
        cristinapolis: 'CRISTINÁPOLIS/SE',
        estancia: 'FILIAL ESTANCIA/SE',
        santaMaria: 'FILIAL SANTA MARIA/SE',
        tobiasBarreto: 'FILIAL TOBIAS BARRETO/SE',
        indiaroba: 'INDIAROBA/SE',
        japaratuba: 'JAPARATUBA/SE',
        japoata: 'JAPOATÃ/SE',
        joaoAlves: 'JOÃO ALVES/SE',
        lamarao: 'LAMARÃO/SE',
        loteamentoJeova: 'LOTEAMENTO JEOVÁ/SE',
        matrizAracaju: 'MATRIZ ARACAJU/SE',
        muribeca: 'MURIBECA/SE',
        pacatuba: 'PACATUBA/SE',
        pedrinhas: 'PEDRINHAS/SE',
        piabeta: 'PIABETA/SE',
        portoDoMato: 'PORTO DO MATO/SE',
        propria: 'PROPRIÁ/SE',
        rosarioDoCatete: 'ROSÁRIO DO CATETE/SE',
        santaRosaDeLima: 'SANTA ROSA DE LIMA/SE',
        santoAmaro: 'SANTO AMARO/SE',
        sindicatoDosTrabalhadoresIndiaroba: 'SINDICATO DOS TRABALHADORES RURAIS EM INDIAROBA/SE',
        sinttra: 'SINTTRA/SE',
        umbauba: 'UMBAÚBA/SE',
    },
    go: {
        ceuAzul: 'CÉU AZUL',
        aguasLindas: 'FILIAL ÁGUAS LINDAS/GO',
        jardimInga: 'JARDIM INGÁ',
        lunabelNovoGama: 'LUNABEL NOVO GAMA',
        monteAlto: 'MONTE ALTO',
        novoGama: 'NOVO GAMA/DF',
        padreBernardo: 'PADRE BERNARDO',
        santoAntonioDoDescoberto: 'SANTO ANTÔNIO DO DESCOBERTO/GO',
        valparaiso: 'VALPARAÍSO/GO',
    }
}
