export * from '@services/fileHandler/utils/isPrev.services'
export * from '@services/fileHandler/utils/isTRT.services'
export * from '@services/fileHandler/utils/isJF.services'
export * from '@services/fileHandler/fileHandlerExcel.services'
export * from '@services/fileHandler/fileHandlerWord.services'
export * from '@services/fileHandler/fileHandlerPDFS.services'