export * from '@services/clientes/utils/extrairIdBuscaClienteByCPFHtml.services'
export * from '@services/clientes/utils/extrairDadosRequisicaoClienteHtml.services'
export * from '@services/clientes/utils/extractValueFromSelectProcessForm.services'
export * from '@services/clientes/get/getCliente.services'
export * from '@services/clientes/create/createCliente.services'