export * from '@services/clientes/utils/extrairIdBuscaClienteByCPFHtml'
export * from '@services/clientes/utils/extrairDadosRequisicaoClienteHtml'
export * from '@services/clientes/get/getDataCliente'
export * from '@services/clientes/get/getClienteService'
export * from '@services/clientes/create/createClienteService'